prefix=${CMAKE_INSTALL_PREFIX}
libdir=${PKG_CONFIG_LIBDIR}
includedir=${PKG_CONFIG_INCLUDEDIR}

Name: ${PROJECT_NAME}
Description: ${PROJECT_DESCRIPTION}
Version: ${PROJECT_VERSION}
Requires: ${PKG_CONFIG_REQUIRES}
Cflags: ${PKG_CONFIG_CFLAGS}
Libs: ${PKG_CONFIG_LIBS}
